### ISSUE TITLE
`NotificationStore.notificationCount` can become negative under certain circumstances

### ISSUE THREAD

**Issue by SimonSchick** [magicbell-io/magicbell-core#7]
We ran into an issue earlier where when calling `Notification.markAsRead()` multiple times on the same notification the, `notificationCount` on the `NotifiticationStore` would go negative within a session, reloading the session/window would fix it.

I understand https://github.com/magicbell-io/magicbell-core/blob/9c7e1d04d386aa28a9f7e3507776fb2e7f720b4f/src/stores/NotificationStore.ts#L105 should prevent this behavior, but assume that https://github.com/magicbell-io/magicbell-core/blob/9c7e1d04d386aa28a9f7e3507776fb2e7f720b4f/src/stores/NotificationStore.ts#L118 somehow receives bad data and simply overrides the value, based on the short dive I took into the code base this could be an issue on your server impl.

We don't have a great repro at this time since we use the react SDK in a rather hard-to-extract way.

cc @aakashbapna

**Comment by smeijer** [comment]
Closing this issue as we've moved to a monorepo. Please create a new ticket there if this issue persists. Thanks.

https://github.com/magicbell-io/magicbell-js
